### PR TITLE
Add index files for /implement and /extend

### PR DESCRIPTION
**Pull request by tchssk**

### CODE REVIEW

**Comment by raphael** [comment]
Nice catch, thanks!

**Comment by tchssk** [comment]
It seems the deploy was failed. @raphael

**Comment by raphael** [comment]
Thank you! Looks like the last one worked ¯\_(ツ)_/¯

**Comment by tchssk** [comment]
It seems #132 #133 #134 were deployed but #131 was not 🤔

**Comment by tchssk** [comment]
Now it's live, thank you!

**Pull request merged**
