### PR TITLE
Use multilingual mode of hugo

### PR DESCRIPTION
**Pull request by tchssk**
This is related to #42.

It's finally over.
This PR makes it to use [multilungual mode](https://gohugo.io/content/multilingual/) of hugo.

### CODE REVIEW

**Comment by raphael** [comment]
Thank you so much!

**Comment by raphael** [comment]
And it's now live! I did notice a small glitch: the link in the footer under "Languages" points to the Japanese version of the page even for the Japanese page - it should say "English" and point to the English version. Thank you again!

**Comment by tchssk** [comment]
Oh also I did notice some points needing improvements in README. I'll fix both later.

**Comment by tchssk** [comment]
I forgot. Would you fast-forward `ja` branch to `master`? @raphael

**Comment by raphael** [comment]
Done. Something I noticed but haven't had a chance to look into yet is that switching to the multilingual support broke the `GoDoc` link...

**Comment by tchssk** [comment]
Oh...I created a new PR to fix that. Would you fast-forward again after merging?

**Pull request merged**
