### PR TITLE
Make easy to identify important links

### PR DESCRIPTION
**Pull request by gagliardetto**
Make easy to find the Reference (now with title and in bold) and Github links on the web page.

Having some text inside the links will make sure that those two links are show on mobile devices (right now, no links to /reference and the github page are shown in the navigation on mobile devices because they contain no text.)

### CODE REVIEW

**Comment by raphael** [comment]
Thank you for the PR! The changes cause a few glitches though. The goa logo is not on the same line as the menu anymore and the "edit" button wraps. I've attached a screenshot to illustrate:

screenshot from 2016-09-16 08-59-17

**Comment by gagliardetto** [comment]
How about this?

I changed a couple of values in style.css. I don't like either the inline style, but I can't find in the css the part responsible for the width of the <li> tag containing the search <input>. Any ideas?

schermata del 2016-09-16 19-36-48

**Comment by raphael** [comment]
Maybe we could make the goa logo a bit smaller to gain some space also I wonder if we could hide the text for "github" with css. We'd keep the text so it appears on mobile devices but have it hidden on non mobile devices (maybe by adding a rule in the media section https://github.com/goadesign/goa.design/blob/master/static/css/style.css#L794).

This is where the style of the `<li>` tag is controlled: https://github.com/goadesign/goa.design/blob/master/static/css/style.css#L794 however the size is limited by the size of the container too so changes are not always intuitive...

Thank you for working on this!

**Comment by gagliardetto** [comment]
It seems that bootstrap's `hidden-*` don't work as expected, so I wrote some custom media queries (following bootstrap's width sizes). 

Right now, the Github text will be hidden on screens with width 720px and up.

What do you think?


schermata del 2016-09-16 21 12 43

**Comment by gagliardetto** [comment]
I realized now that we could just add a `<span style="display:none">Github</span>` without using media queries, and will be hidden everywhere except for the mobile menu.

**Comment by raphael** [comment]
That would probably be better indeed, care to make that change?

**Comment by gagliardetto** [comment]
Done.

**Comment by raphael** [comment]
Thanks for all the work!

**Pull request merged**
