### PR TITLE
Update /ja/learn/getting-started

### PR DESCRIPTION
**Pull request by tchssk**
* Update japanese translations for #137
* Would you review this? @ikawaha

### CODE REVIEW

**Review by ikawaha — APPROVED** [review]
@tchssk ごめんなさい。完全に見落としていました。ok とおもいます！

**Comment by tchssk** [comment]
This has been reviewed. I'll merge this. @raphael

**Comment by tchssk** [comment]
It seems the deploys was skipped. https://github.com/goadesign/goa.design/actions/runs/2101379417
Would you take a look? @raphael

**Comment by raphael** [comment]
It should be deployed now. I removed the extra check that seemed to be causing issues (https://github.com/goadesign/goa.design/commit/23c64b2b79ed347dda65733cedf12588be4ecb16).

**Comment by tchssk** [comment]
Thank you!

**Pull request merged**
