### PR TITLE
Add docs describing the EntryPoint interface for a Store

### PR DESCRIPTION
**Pull request by aslakknutsen**

### CODE REVIEW

**Comment by aslakknutsen** [comment]
@raphael just FYI, then feature has not been committed to Gorma yet. :) But doc before the feature got to be some kinda new record. hehe

**Comment by raphael** [comment]
oh whoops thank you, I'll revert

**Comment by raphael** [comment]
hmm I guess I can't reopen this directly from GitHub...

**Comment by raphael** [comment]
What a mess - this is now #30

**Pull request merged**
