### PR TITLE
Translate into Japanese

### PR DESCRIPTION
**Pull request by tchssk**
goa is an amazing library but it is not very popular in Japan at this point.
I would like to introduce goa to more Japanese people so I translate goa.design into Japanese.
This is an initial pull request so it includes only a few parts.

- index
- header
- footer

I will work on another parts if you like it.
Thank you.

### CODE REVIEW

**Comment by raphael** [comment]
I love the idea! How do you see this work going forward? Especially with v2 coming some time in the future there may be big changes to the site. Maybe there should be a branch in the repo so that we can keep track of the last time master was merged? Then the process would be:

1. Merge master into the "ja" branch
2. Add commit to the ja branch to translate new content
3. Merge back ja branch into master
4. Repeat

**Comment by tchssk** [comment]
That's a good idea. We should keep tracking which revision is base of the translated documents. I looked for a useful reference project, the way of Riot is looking good too.

https://github.com/riot/riot.github.io/blob/f8685e13024bf51827317d11d9800e3686d8960b/CONTRIBUTING.md

**Comment by tchssk** [comment]
I think we need at least two contributors for translation. One is a translator, and the other is a reviewer (Translator and reviewer are not fixed roles).

I talked with @ikawaha about this. He said that he would help us 🙌

**Comment by raphael** [comment]
Thanks for the pointer on the riot docs, I added instructions on how to contribute translations to the README based on it.

**Comment by raphael** [comment]
I'll merge this for now. I'll also create a `ja` branch so you can send PRs to it in the future.

**Comment by tchssk** [comment]
Thank you!

**Comment by raphael** [comment]
So I've been battling hugo to make it generate sections for secondary level files so we could have sections with the current layout for `en/design` etc. Not having these sections causes the pages to be blank. 

I've made it work (see https://github.com/raphael/hugo/commit/36112abeeeb6f0b985f8f9edfadd5155bdd44d43) but I'm now realizing that hugo has multilingual support built-in since v0.17, see https://github.com/spf13/hugo/blob/d8c372cad52c44f76943f8c5592dc02a1eb65409/docs/content/content/multilingual.md. This is probably the proper way to do it. It means a new layout and new config files. Do you think you could create a new PR that adopts the setup described in v0.17? Thank you!

**Comment by tchssk** [comment]
Oh I didn't check v0.17 of hugo. It looks good for this work. OK I will create a new PR but are you going to work on master branch? Which commit should I use for base of working?

**Comment by raphael** [comment]
Awesome thank you! Since we are still setting things up I would say use the `master` branch for now. Once everything is properly hooked up with `v0.17` we can start using the new "translation flow".

**Comment by tchssk** [comment]
OK. I'll send a new PR.

**Pull request merged**
